#!/usr/bin/env python3
"""
Install hooks so this project's .env is loaded in the venv and the shell.

- Python: sitecustomize.py loads .env on interpreter start (when cwd is in repo).
- Shell:  sourcing bin/activate exports variables from the repo-root .env.

Run once after creating or recreating .venv:
    .venv/bin/python scripts/install_venv_env_hook.py
"""

from __future__ import annotations

from pathlib import Path

MARKER = "# >>> DAIR3 project .env"
MARKER_END = "# <<< DAIR3 project .env"
DEACTIVATE_MARKER = "# DAIR3: unset project .env variables"

SITE_CUSTOMIZE = '''\
"""Auto-load DAIR3-Workshop .env (installed by scripts/install_venv_env_hook.py)."""
try:
    from pathlib import Path
    from dotenv import load_dotenv

    def _find_project_root():
        cwd = Path.cwd().resolve()
        for directory in (cwd, *cwd.parents):
            if (directory / "pyproject.toml").is_file() and (directory / ".env").is_file():
                return directory
        return None

    root = _find_project_root()
    if root is not None:
        load_dotenv(root / ".env", override=False)
except Exception:
    pass
'''

LOAD_PROJECT_ENV_SH = r'''# Sourced by venv activate — exports repo-root .env into the shell.
# Generated by scripts/install_venv_env_hook.py; do not edit by hand.

if [ -z "${VIRTUAL_ENV:-}" ]; then
    return 0 2>/dev/null || true
fi

_dair3_env_file="${VIRTUAL_ENV}/../.env"
if [ ! -f "$_dair3_env_file" ]; then
    unset _dair3_env_file
    return 0 2>/dev/null || true
fi

_dair3_exports="$("${VIRTUAL_ENV}/bin/python" - <<'PY'
import os
import shlex
from pathlib import Path

from dotenv import dotenv_values

venv = Path(os.environ["VIRTUAL_ENV"])
values = dotenv_values(venv.parent / ".env")
keys = []
lines = []
for key, value in values.items():
    if value is None:
        continue
    keys.append(key)
    lines.append(f"export {key}={shlex.quote(value)}")
if keys:
    lines.append('_DAIR3_DOTENV_VARS="' + " ".join(keys) + '"')
print("\n".join(lines))
PY
)"

if [ -n "$_dair3_exports" ]; then
    eval "$_dair3_exports"
fi

unset _dair3_env_file _dair3_exports
'''

ACTIVATE_APPEND = f"""
{MARKER}
if [ -n "${{VIRTUAL_ENV:-}}" ] && [ -f "${{VIRTUAL_ENV}}/bin/load-project-env.sh" ]; then
    # shellcheck source=/dev/null
    . "${{VIRTUAL_ENV}}/bin/load-project-env.sh"
fi
{MARKER_END}
"""

DEACTIVATE_INSERT = f"""    {DEACTIVATE_MARKER}
    if ! [ -z "${{_DAIR3_DOTENV_VARS+_}}" ] ; then
        for _dair3_var in $_DAIR3_DOTENV_VARS; do
            unset "$_dair3_var" 2>/dev/null || true
        done
        unset _DAIR3_DOTENV_VARS
    fi
"""

FISH_APPEND = f"""
{MARKER}
if test -n "$VIRTUAL_ENV"; and test -f "$VIRTUAL_ENV/bin/load-project-env.fish"
    source "$VIRTUAL_ENV/bin/load-project-env.fish"
end
{MARKER_END}
"""

FISH_DEACTIVATE_INSERT = f"""    {DEACTIVATE_MARKER}
    if set -q _DAIR3_DOTENV_VARS
        for _dair3_var in $_DAIR3_DOTENV_VARS
            set -e $_dair3_var
        end
        set -e _DAIR3_DOTENV_VARS
    end
"""

LOAD_PROJECT_ENV_FISH = r'''# Sourced by venv activate.fish — exports repo-root .env into the shell.
# Generated by scripts/install_venv_env_hook.py; do not edit by hand.

if test -z "$VIRTUAL_ENV"
    exit 0
end

set -l _dair3_env_file "$VIRTUAL_ENV/../.env"
if not test -f $_dair3_env_file
    exit 0
end

set -l _dair3_exports (env VIRTUAL_ENV=$VIRTUAL_ENV "$VIRTUAL_ENV/bin/python" -c '
import os
import shlex
from pathlib import Path
from dotenv import dotenv_values

venv = Path(os.environ["VIRTUAL_ENV"])
values = dotenv_values(venv.parent / ".env")
keys = []
lines = []
for key, value in values.items():
    if value is None:
        continue
    keys.append(key)
    lines.append(f"export {key}={shlex.quote(value)}")
if keys:
    lines.append("set -gx _DAIR3_DOTENV_VARS " + " ".join(keys))
for line in lines:
    print(line)
')

for _line in $_dair3_exports
    eval $_line
end
'''


def _patch_activate(activate_path: Path) -> None:
    text = activate_path.read_text(encoding="utf-8")
    if MARKER in text:
        return

    if DEACTIVATE_MARKER not in text:
        needle = "    if ! [ -z \"${_OLD_VIRTUAL_PYTHONHOME+_}\" ] ; then"
        if needle not in text:
            raise SystemExit(f"Could not patch deactivate() in {activate_path}")
        text = text.replace(
            needle,
            DEACTIVATE_INSERT + "\n" + needle,
            1,
        )

    text = text.rstrip() + "\n" + ACTIVATE_APPEND
    activate_path.write_text(text, encoding="utf-8")
    print(f"Patched {activate_path}")


def _patch_activate_fish(activate_path: Path) -> None:
    text = activate_path.read_text(encoding="utf-8")
    if MARKER in text:
        return

    if DEACTIVATE_MARKER not in text:
        needle = "    # reset old environment variables\n    if test -n \"$_OLD_VIRTUAL_PATH\""
        if needle not in text:
            raise SystemExit(f"Could not patch deactivate in {activate_path}")
        text = text.replace(needle, "    # reset old environment variables\n" + FISH_DEACTIVATE_INSERT + "\n    if test -n \"$_OLD_VIRTUAL_PATH\"", 1)

    text = text.rstrip() + "\n" + FISH_APPEND
    activate_path.write_text(text, encoding="utf-8")
    print(f"Patched {activate_path}")


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    venv = repo_root / ".venv"
    if not venv.is_dir():
        raise SystemExit(f"No .venv at {venv}. Create it with: uv sync")

    bin_dir = venv / "bin"
    (bin_dir / "load-project-env.sh").write_text(LOAD_PROJECT_ENV_SH, encoding="utf-8")
    (bin_dir / "load-project-env.fish").write_text(LOAD_PROJECT_ENV_FISH, encoding="utf-8")
    print(f"Wrote {bin_dir / 'load-project-env.sh'}")
    print(f"Wrote {bin_dir / 'load-project-env.fish'}")

    _patch_activate(bin_dir / "activate")
    _patch_activate_fish(bin_dir / "activate.fish")

    site_packages = next((venv / "lib").glob("python*/site-packages"), None)
    if site_packages is None:
        raise SystemExit("Could not find site-packages in .venv")

    target = site_packages / "sitecustomize.py"
    target.write_text(SITE_CUSTOMIZE, encoding="utf-8")
    print(f"Wrote {target}")
    print()
    print("Shell:  source .venv/bin/activate   # exports .env into your terminal")
    print("Python: restart kernels/processes if already running")


if __name__ == "__main__":
    main()
